CREATE TABLE IF NOT EXISTS datos_nacimiento (
    id      INTEGER NOT NULL,
    dato    TEXT NOT NULL);

INSERT INTO datos_nacimiento (id, dato) values
    (1, "NOMBRE TITULAR"),
    (2, "APELLIDO PATERNO TITULAR"),
    (3, "APELLIDO MATERNO TITULAR"),
    (4, "NOMBRE DEL PADRE"),
    (5, "APELLIDO PATERNO DEL PADRE"),
    (6, "APELLIDO MATERNO DEL PADRE"),
    (7, "NOMBRE DE LA MADRE"),
    (8, "APELLIDO PATERNO DE LA MADRE"),
    (9, "APELLIDO MATERNO DE LA MADRE"),
    (10, "FECHA DE NACIMIENTO"),
    (11, "FECHA DE REGISTRO");



CREATE TABLE IF NOT EXISTS datos_matrimonio (
    id      INTEGER NOT NULL,
    dato    TEXT NOT NULL);

INSERT INTO datos_matrimonio (id, dato) values
    (1, "NOMBRE DEL CONTRAYENTE"),
    (2, "APELLIDO PATERNO DEL CONTRAYENTE"),
    (3, "APELLIDO MATERNO DEL CONTRAYENTE"),
    (4, "NOMBRE DE LA CONTRAYENTE"),
    (5, "APELLIDO PATERNO DE LA CONTRAYENTE"),
    (6, "APELLIDO MATERNO DE LA CONTRAYENTE"),
    (7, "FECHA DE REGISTRO");



CREATE TABLE IF NOT EXISTS datos_defuncion (
    id      INTEGER NOT NULL,
    dato    TEXT NOT NULL);

INSERT INTO datos_defuncion (id, dato) values
    (1, "NOMBRE"),
    (2, "APELLIDO PATERNO"),
    (3, "APELLIDO MATERNO");
